## 服务端口号
server:
  port: 8080

spring:
  application:
    name: project
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhang.1234
  ## 设置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5t6LhrxVWBXA5wnZFsWx
      keysecret: rCFDxAmaTQD8JIKoXagBggjGZcWpUD
      bucketname: supercat-project

